### ISSUE TITLE
--only_for_testing-ignore-signer flag missing in create_image.sh

### ISSUE THREAD

**Issue by mostermann96** [scontain/flask_example#5]
When running 
./create_image.sh on a new machine 
`docker run --device=/dev/isgx -it registry.scontain.com:5050/sconecuratedimages/kubernetes:hello-k8s-scone0.1 sh -c '
scone cas attest -G --only_for_testing-debug  4-2-1.scone-cas.cf 4cd0fe54d3d8d787553b7dac7347012682c402220acd062e4d0da3bbe10a1c2c >/dev/null &&  scone cas show-certificate'` 
causes 
`error: The following required arguments were not provided:
    --only_for_testing-ignore-signer
`
Simply adding the flag resolves the issue

**Comment by clenimar** [comment]
closed by #6
